env:
  sumocfg_path: 'rl_arterial_7roads_scene/standard.sumocfg'
  gui: False
  inference: False
  dynamic_flow: True
  flow_range: [9, 19]
  max_episode_steps: 1600
  green_duration: 10
  yellow_duration: 3
  tls: ['1', '3', '4', '5', '7', '6', '2']
  obs:
    obs_type: [phase, traffic_volumn, queue_len]
    traffic_volumn_ratio: 7.5
    use_centralized_obs: True
  action:
    action_type: change
    use_multi_discrete: True
  reward:
    reward_type: 
      pressure: 1.0